Repository wp-cli/export-command, pull requests merged in 2019-04, with the labels that each got.

#54 fix non-writable directory not identified as such
  src/Export_Command.php
Labels: bug

#55 Move PHP 5.4 tests from `WP_VERSION` `latest` to `5.1`
  .travis.yml
Labels: scope:distribution

#57 Enhancement: Add PHP 7.3 to Travis CI build matrix
  .travis.yml
Labels: command:export, scope:testing

#58 Implement CS checking based on the `WP_CLI_CS` ruleset
  .distignore
  .gitignore
  composer.json
  export-command.php
  features/export.feature
  functions.php
  phpcs.xml.dist
  src/Export_Command.php
  src/WP_Export_Base_Writer.php
  src/WP_Export_File_Writer.php
  src/WP_Export_Oxymel.php
  src/WP_Export_Query.php
  src/WP_Export_Returner.php
  src/WP_Export_Split_Files_Writer.php
  src/WP_Export_Stdout_Writer.php
  src/WP_Export_WXR_Formatter.php
  src/WP_Export_XML_Over_HTTP.php
  src/WP_Map_Iterator.php
  src/WP_Post_IDs_Iterator.php
Labels: scope:testing
